# pylint: disable=missing-function-docstring

from entities import SongEntity
from main import AppleMusicParser


def test_xml_reader() -> None:
    apple_music_reader = AppleMusicParser()
    first = next(apple_music_reader.read())
    assert first == SongEntity(author="Amon Amarth", name="As Loke Falls")


def test_raw_xml_row_parser() -> None:
    raw_data: list[dict[str, str | None]] = [
        {"key": "Track ID"},
        {"integer": "1172"},
        {"key": "Name"},
        {"string": "As Loke Falls"},
        {"key": "Artist"},
        {"string": "Amon Amarth"},
        {"key": "Album Artist"},
        {"string": "Amon Amarth"},
        {"key": "Album"},
        {"string": "Deceiver of the Gods"},
        {"key": "Genre"},
        {"string": "Metal"},
        {"key": "Kind"},
        {"string": "Аудіофайл Apple Music AAC"},
        {"key": "Size"},
        {"integer": "10231920"},
        {"key": "Total Time"},
        {"integer": "278777"},
        {"key": "Disc Number"},
        {"integer": "1"},
        {"key": "Disc Count"},
        {"integer": "1"},
        {"key": "Track Number"},
        {"integer": "2"},
        {"key": "Track Count"},
        {"integer": "10"},
        {"key": "Year"},
        {"integer": "2013"},
        {"key": "Date Modified"},
        {"date": "2023-01-18T20:00:56Z"},
        {"key": "Date Added"},
        {"date": "2023-01-18T20:00:56Z"},
        {"key": "Bit Rate"},
        {"integer": "256"},
        {"key": "Sample Rate"},
        {"integer": "44100"},
        {"key": "Play Count"},
        {"integer": "7"},
        {"key": "Play Date"},
        {"integer": "3787260886"},
        {"key": "Play Date UTC"},
        {"date": "2024-01-04T22:54:46Z"},
        {"key": "Release Date"},
        {"date": "2013-06-19T07:00:00Z"},
        {"key": "Favorited"},
        {"true": None},
        {"key": "Loved"},
        {"true": None},
        {"key": "Artwork Count"},
        {"integer": "1"},
        {"key": "Sort Album"},
        {"string": "Deceiver of the Gods"},
        {"key": "Sort Artist"},
        {"string": "Amon Amarth"},
        {"key": "Sort Name"},
        {"string": "As Loke Falls"},
        {"key": "Persistent ID"},
        {"string": "9B9354F2A4ECEE7A"},
        {"key": "Track Type"},
        {"string": "Remote"},
        {"key": "Apple Music"},
        {"true": None},
    ]

    result: dict[str, str] = AppleMusicParser.parse_xml_raw_as_song(raw_data)
    assert result == {
        "Track ID": "1172",
        "Name": "As Loke Falls",
        "Artist": "Amon Amarth",
        "Album Artist": "Amon Amarth",
        "Album": "Deceiver of the Gods",
        "Genre": "Metal",
        "Kind": "Аудіофайл Apple Music AAC",
        "Size": "10231920",
        "Total Time": "278777",
        "Disc Number": "1",
        "Disc Count": "1",
        "Track Number": "2",
        "Track Count": "10",
        "Year": "2013",
        "Date Modified": "2023-01-18T20:00:56Z",
        "Date Added": "2023-01-18T20:00:56Z",
        "Bit Rate": "256",
        "Sample Rate": "44100",
        "Play Count": "7",
        "Play Date": "3787260886",
        "Play Date UTC": "2024-01-04T22:54:46Z",
        "Release Date": "2013-06-19T07:00:00Z",
        "Favorited": "false",
        "Loved": "false",
        "Artwork Count": "1",
        "Sort Album": "Deceiver of the Gods",
        "Sort Artist": "Amon Amarth",
        "Sort Name": "As Loke Falls",
        "Persistent ID": "9B9354F2A4ECEE7A",
        "Track Type": "Remote",
        "Apple Music": "false",
    }
